import { describe, expect, it } from "vitest";

import {
  macBundleVersionFromSemver,
  macMarketingVersionFromSemver,
  syncChangelogForVersion,
  syncNpmLockfileVersion,
  updatePlistStringValue,
  updateCargoLockPackageVersion,
  updateWindowsResourceFlags,
  updateWindowsResourceVersion,
  updateWindowsAssemblyIdentityVersion,
  updateWindowsShellResourceDestinations,
  windowsPackageVersionFromSemver,
} from "../../scripts/sync-version-helpers.js";

const resource = `#ifdef _DEBUG
 FILEFLAGS VS_FF_DEBUG | VS_FF_PRERELEASE
#else
 FILEFLAGS VS_FF_PRERELEASE
#endif`;

describe("Cargo.lock package version", () => {
  const lockfile = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "anyhow"
version = "1.0.0"

[[package]]
name = "freeace"
version = "0.6.0-beta.10"
dependencies = [
 "anyhow",
]
`;

  it("updates only the named package version", () => {
    expect(updateCargoLockPackageVersion(lockfile, "freeace", "0.6.0-beta.11"))
      .toBe(`# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "anyhow"
version = "1.0.0"

[[package]]
name = "freeace"
version = "0.6.0-beta.11"
dependencies = [
 "anyhow",
]
`);
  });

  it("fails when the package entry is missing", () => {
    expect(() =>
      updateCargoLockPackageVersion(lockfile, "missing", "1.0.0"),
    ).toThrow(/missing \[\[package\]\]/);
  });
});

describe("Windows resource version flags", () => {
  it("marks beta builds as prerelease", () => {
    expect(updateWindowsResourceFlags(resource, "0.6.0-beta.4")).toBe(resource);
  });

  it("removes prerelease flags from stable builds", () => {
    expect(updateWindowsResourceFlags(resource, "0.6.0")).toBe(`#ifdef _DEBUG
 FILEFLAGS VS_FF_DEBUG
#else
 FILEFLAGS 0
#endif`);
  });

  it("fails if the expected resource block is missing", () => {
    expect(() => updateWindowsResourceFlags("FILEFLAGS 0", "0.6.0")).toThrow(
      /FILEFLAGS block was not found/,
    );
  });
});

describe("Windows resource version fields", () => {
  const fullResource = ` FILEVERSION 0,5,0,1
 PRODUCTVERSION 0,5,0,1
${resource}
      VALUE "FileVersion", "0.5.0\\0"
      VALUE "ProductVersion", "0.5.0\\0"`;

  it("updates every required numeric and string version field", () => {
    const updated = updateWindowsResourceVersion(fullResource, "0.6.0");
    expect(updated).toContain(" FILEVERSION 0,6,0,65535");
    expect(updated).toContain(" PRODUCTVERSION 0,6,0,65535");
    expect(updated).toContain('VALUE "FileVersion", "0.6.0\\0"');
    expect(updated).toContain('VALUE "ProductVersion", "0.6.0\\0"');
  });

  it("fails if any expected RC version replacement is missing", () => {
    expect(() =>
      updateWindowsResourceVersion(
        fullResource.replace(/^ PRODUCTVERSION .+\n/m, ""),
        "0.6.0",
      ),
    ).toThrow(/PRODUCTVERSION.*exactly once/);
  });
});

describe("Windows assembly identity version", () => {
  const manifest = `<assembly><assemblyIdentity name="freeace" version="0.6.0.0"/></assembly>`;

  it("uses the ordered Windows package version", () => {
    expect(updateWindowsAssemblyIdentityVersion(manifest, "0.6.1-beta.2")).toBe(
      `<assembly><assemblyIdentity name="freeace" version="0.6.1.2"/></assembly>`,
    );
  });

  it("fails closed when the identity version is missing or duplicated", () => {
    expect(() =>
      updateWindowsAssemblyIdentityVersion("<assembly/>", "0.6.1"),
    ).toThrow(/found 0/);
    expect(() =>
      updateWindowsAssemblyIdentityVersion(`${manifest}${manifest}`, "0.6.1"),
    ).toThrow(/found 2/);
  });
});

describe("Windows package version", () => {
  it("keeps beta, stable, and the next patch monotonically ordered", () => {
    const versions = [
      "0.6.0-beta.1",
      "0.6.0-beta.14",
      "0.6.0",
      "0.6.1-beta.0",
    ].map(windowsPackageVersionFromSemver);

    expect(versions).toEqual(["0.6.0.1", "0.6.0.14", "0.6.0.65535", "0.6.1.0"]);
    for (let index = 1; index < versions.length; index += 1) {
      const previous = versions[index - 1].split(".").map(Number);
      const current = versions[index].split(".").map(Number);
      const differingIndex = current.findIndex(
        (part, partIndex) => part !== previous[partIndex],
      );
      expect(differingIndex).toBeGreaterThanOrEqual(0);
      expect(current[differingIndex]).toBeGreaterThan(previous[differingIndex]);
    }
  });

  it("rejects unsupported prerelease forms and out-of-range components", () => {
    expect(() => windowsPackageVersionFromSemver("0.6.0-preview.1")).toThrow(
      /cannot be represented/,
    );
    expect(() => windowsPackageVersionFromSemver("0.6.0-alpha.1")).toThrow(
      /cannot be represented/,
    );
    expect(() => windowsPackageVersionFromSemver("0.6.0-rc.1")).toThrow(
      /cannot be represented/,
    );
    expect(() => windowsPackageVersionFromSemver("0.6.0-beta.014")).toThrow(
      /cannot be represented/,
    );
    expect(() => windowsPackageVersionFromSemver("0.6.0-beta.65535")).toThrow(
      /0-65534/,
    );
    expect(() => windowsPackageVersionFromSemver("65536.0.0")).toThrow(
      /exceeds 65535/,
    );
  });
});

describe("Windows shell resource destinations", () => {
  it("writes every shell artifact to the concrete release directory", () => {
    const resources = {
      "windows/shell/out/freeace_shell.dll": "old/freeace_shell.dll",
      "windows/shell/out/freeace_extract_shell.dll":
        "old/freeace_extract_shell.dll",
      "windows/shell/out/FreeAceContextMenu.msix": "old/FreeAceContextMenu.msix",
      "windows/shell/out/FreeAceExtractContextMenu.msix":
        "old/FreeAceExtractContextMenu.msix",
      "../scripts/register-windows-context-menu.ps1":
        "old/register-windows-context-menu.ps1",
      "unrelated.txt": "keep/unrelated.txt",
    };
    const config = { bundle: { resources } };

    const updated = updateWindowsShellResourceDestinations(
      config,
      "0.6.0-beta.14",
    );

    expect(updated.bundle.resources).toEqual({
      "windows/shell/out/freeace_shell.dll":
        "shell-0.6.0-beta.14/freeace_shell.dll",
      "windows/shell/out/freeace_extract_shell.dll":
        "shell-0.6.0-beta.14/freeace_extract_shell.dll",
      "windows/shell/out/FreeAceContextMenu.msix":
        "shell-0.6.0-beta.14/FreeAceContextMenu.msix",
      "windows/shell/out/FreeAceExtractContextMenu.msix":
        "shell-0.6.0-beta.14/FreeAceExtractContextMenu.msix",
      "../scripts/register-windows-context-menu.ps1":
        "shell-0.6.0-beta.14/register-windows-context-menu.ps1",
      "unrelated.txt": "keep/unrelated.txt",
    });
    expect(config.bundle.resources).toBe(resources);
  });

  it("fails when a required shell artifact is removed from packaging", () => {
    expect(() =>
      updateWindowsShellResourceDestinations(
        { bundle: { resources: {} } },
        "0.6.0-beta.14",
      ),
    ).toThrow(/missing shell resource/);
  });
});

describe("macOS bundle version", () => {
  it("converts prerelease and stable SemVer versions into ordered numeric builds", () => {
    expect(macBundleVersionFromSemver("0.6.0-beta.4")).toBe("0.6.3004");
    expect(macBundleVersionFromSemver("0.6.0-beta.30")).toBe("0.6.3030");
    expect(macBundleVersionFromSemver("0.6.0")).toBe("0.6.9999");
    expect(macBundleVersionFromSemver("0.6.1-beta.1")).toBe("0.6.13001");
  });

  it("rejects unsupported prerelease version forms", () => {
    expect(() => macBundleVersionFromSemver("0.6.0-preview.1")).toThrow(
      /cannot be represented/,
    );
    expect(() => macBundleVersionFromSemver("0.6.0-alpha.1")).toThrow(
      /cannot be represented/,
    );
    expect(() => macBundleVersionFromSemver("0.6.0-rc.1")).toThrow(
      /cannot be represented/,
    );
    expect(() => macBundleVersionFromSemver("0.6.0-beta.04")).toThrow(
      /cannot be represented/,
    );
    expect(() => macBundleVersionFromSemver("0.6.0-beta.6999")).toThrow(
      /0-6998/,
    );
  });
});

describe("macOS marketing version", () => {
  it("uses the numeric SemVer core for stable and prerelease builds", () => {
    expect(macMarketingVersionFromSemver("0.6.0-beta.13")).toBe("0.6.0");
    expect(macMarketingVersionFromSemver("1.2.3")).toBe("1.2.3");
  });

  it("rejects unsupported version forms", () => {
    expect(() => macMarketingVersionFromSemver("1.2")).toThrow(
      /cannot be represented/,
    );
    expect(() => macMarketingVersionFromSemver("1.2.3-preview.1")).toThrow(
      /cannot be represented/,
    );
  });
});

describe("plist version synchronization", () => {
  it("updates exactly one string-valued key", () => {
    const plist = "<dict><key>CFBundleVersion</key><string>1</string></dict>";
    expect(updatePlistStringValue(plist, "CFBundleVersion", "0.6.131")).toBe(
      "<dict><key>CFBundleVersion</key><string>0.6.131</string></dict>",
    );
  });

  it("fails closed when a key is missing or duplicated", () => {
    expect(() =>
      updatePlistStringValue("<dict/>", "CFBundleVersion", "1"),
    ).toThrow(/found 0/);
    expect(() =>
      updatePlistStringValue(
        "<key>Build</key><string>1</string><key>Build</key><string>2</string>",
        "Build",
        "3",
      ),
    ).toThrow(/found 2/);
  });
});

describe("CHANGELOG version synchronization", () => {
  const intro =
    "FreeAce! A cross platform 7Z gui frontend built on Tauri V2!\n\n";
  const downloadBlock = `# ⬇️ Downloads

| win |
| [x64](https://github.com/skonester/FreeAce/releases/download/v0.6.1-beta.1/app.exe) |
`;
  const tail = `\n> macOS note\n\n${intro}## Changes in \`v0.6.1-beta.1:\`\n\n- old\n`;

  it("rewrites download URLs to the current tag", () => {
    const synced = syncChangelogForVersion(
      downloadBlock + tail,
      "0.6.1-beta.2",
    );
    expect(synced).toContain("/download/v0.6.1-beta.2/app.exe");
    expect(synced).not.toContain("/download/v0.6.1-beta.1/app.exe");
  });

  it("inserts a new changes section when the version is new", () => {
    const synced = syncChangelogForVersion(
      downloadBlock + tail,
      "0.6.1-beta.2",
    );
    expect(synced).toContain("## Changes in `v0.6.1-beta.2:`");
    expect(synced).toContain("## Changes in `v0.6.1-beta.1:`");
  });
});

describe("package-lock.json version", () => {
  const lockfile = `{
  "name": "freeace",
  "version": "0.6.1-beta.5",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "name": "freeace",
      "version": "0.6.1-beta.5"
    },
    "node_modules/left-pad": {
      "version": "1.3.0"
    }
  }
}
`;

  it("rewrites only the root and packages empty-key version fields", () => {
    const updated = JSON.parse(
      syncNpmLockfileVersion(lockfile, "0.6.1-beta.6"),
    );
    expect(updated.version).toBe("0.6.1-beta.6");
    expect(updated.packages[""].version).toBe("0.6.1-beta.6");
    expect(updated.packages["node_modules/left-pad"].version).toBe("1.3.0");
  });

  it("returns the original text when versions already match", () => {
    const current = lockfile.replaceAll("0.6.1-beta.5", "0.6.1-beta.6");
    expect(syncNpmLockfileVersion(current, "0.6.1-beta.6")).toBe(current);
  });

  it("fails closed when the lockfile packages empty key is missing", () => {
    expect(() =>
      syncNpmLockfileVersion(`{"name":"freeace","version":"1.0.0"}`, "1.0.0"),
    ).toThrow(/packages/);
  });
});
