import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

function readCapability(name: "default" | "extract" | "debug-console"): {
  permissions: string[];
} {
  const file = path.resolve(
    process.cwd(),
    "src-tauri",
    "capabilities",
    `${name}.json`,
  );
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

const INVOKE_RE = /invoke(?:<[^>]+>)?\(\s*["'](\w+)["']/g;
const IMPORT_RE = /from\s+["'](\.[^"']+)["']/g;

function collectInvokes(entryRel: string): Set<string> {
  const srcRoot = path.resolve(process.cwd(), "src");
  const visited = new Set<string>();
  const commands = new Set<string>();

  function visit(file: string): void {
    const abs = path.normalize(file);
    if (visited.has(abs)) return;
    if (!abs.startsWith(srcRoot)) return;
    const base = path.basename(abs);
    if (base.startsWith("e2e-") || base.endsWith(".test.ts")) return;
    if (!fs.existsSync(abs) || !fs.statSync(abs).isFile()) return;
    visited.add(abs);
    const source = fs.readFileSync(abs, "utf8");
    for (const match of source.matchAll(INVOKE_RE)) {
      commands.add(match[1]);
    }
    for (const match of source.matchAll(IMPORT_RE)) {
      const spec = match[1].replace(/\.js$/, "");
      const resolved = path.resolve(path.dirname(abs), spec);
      const candidates = [
        resolved,
        `${resolved}.ts`,
        path.join(resolved, "index.ts"),
      ];
      for (const candidate of candidates) {
        if (fs.existsSync(candidate) && fs.statSync(candidate).isFile()) {
          visit(candidate);
          break;
        }
      }
    }
  }

  visit(path.resolve(process.cwd(), entryRel));
  return commands;
}

function allowPermission(command: string): string {
  return `allow-${command.replaceAll("_", "-")}`;
}

function customAllowPermissions(permissions: string[]): string[] {
  return permissions.filter((permission) => permission.startsWith("allow-"));
}

describe("Tauri capability policy", () => {
  it("keeps generated command permissions aligned with the Rust manifest and handler", () => {
    const buildRs = fs.readFileSync(
      path.resolve(process.cwd(), "src-tauri", "build.rs"),
      "utf8",
    );
    const mainRs = fs.readFileSync(
      path.resolve(process.cwd(), "src-tauri", "src", "main.rs"),
      "utf8",
    );
    const manifestMatch = buildRs.match(
      /const COMMANDS: &\[&str\] = &\[([\s\S]*?)\];/,
    );
    const handlerMatch = mainRs.match(/generate_handler!\[([\s\S]*?)\]\)/);
    expect(manifestMatch?.[1]).toBeDefined();
    expect(handlerMatch?.[1]).toBeDefined();

    const manifestCommands = [
      ...(manifestMatch?.[1].matchAll(/"([^"]+)"/g) ?? []),
    ].map((match) => match[1]);
    const handlerCommands = [
      ...(handlerMatch?.[1].matchAll(/::(\w+),?/g) ?? []),
    ].map((match) => match[1]);
    const generatedPermissions = new Set(
      fs
        .readdirSync(
          path.resolve(
            process.cwd(),
            "src-tauri",
            "permissions",
            "autogenerated",
          ),
        )
        .map((file) => path.basename(file, ".toml")),
    );

    expect(new Set(manifestCommands)).toEqual(new Set(handlerCommands));
    for (const command of handlerCommands) {
      expect(generatedPermissions).toContain(command);
    }
  });

  it("grants only the dialog, updater, process, notification, and shell APIs FreeAce uses", () => {
    const { permissions } = readCapability("default");

    expect(permissions).toEqual(
      expect.arrayContaining([
        "dialog:allow-message",
        "dialog:allow-confirm",
        "dialog:allow-open",
        "dialog:allow-save",
        "shell:default",
        "updater:allow-check",
        "updater:allow-download",
        "updater:allow-install",
        "process:allow-restart",
        "notification:allow-is-permission-granted",
        "notification:allow-request-permission",
        "notification:allow-notify",
      ]),
    );
    expect(permissions).not.toEqual(
      expect.arrayContaining([
        "dialog:default",
        "updater:default",
        "process:default",
        "notification:default",
        "shell:allow-execute",
        "shell:allow-spawn",
      ]),
    );
    expect(permissions).toEqual(
      expect.arrayContaining([
        "core:app:allow-version",
        "core:event:allow-listen",
        "core:event:allow-unlisten",
      ]),
    );
    expect(permissions).not.toContain("core:default");
  });

  it("keeps generated capabilities.json permissions aligned with default.json", () => {
    const { permissions } = readCapability("default");
    const generated = JSON.parse(
      fs.readFileSync(
        path.resolve(
          process.cwd(),
          "src-tauri",
          "gen",
          "schemas",
          "capabilities.json",
        ),
        "utf8",
      ),
    ) as { default?: { permissions?: string[] } };
    expect(new Set(generated.default?.permissions ?? [])).toEqual(
      new Set(permissions),
    );
    expect(generated.default?.permissions).toContain("shell:default");
  });

  it("grants every import-transitive invoke used by extract-window.ts, and no extra allow-*", () => {
    const commands = collectInvokes(path.join("src", "extract-window.ts"));
    expect(commands.size).toBeGreaterThan(0);

    const { permissions } = readCapability("extract");
    const granted = new Set(permissions);
    for (const command of commands) {
      expect(granted, `extract window invokes ${command}`).toContain(
        allowPermission(command),
      );
    }
    const unused = customAllowPermissions(permissions).filter(
      (permission) =>
        ![...commands].some(
          (command) => allowPermission(command) === permission,
        ),
    );
    expect(unused).toEqual([]);
  });

  it("grants every import-transitive invoke used by main.ts, and no extra allow-*", () => {
    const commands = collectInvokes(path.join("src", "main.ts"));
    expect(commands.size).toBeGreaterThan(0);

    const { permissions } = readCapability("default");
    const granted = new Set(permissions);
    for (const command of commands) {
      expect(granted, `main window invokes ${command}`).toContain(
        allowPermission(command),
      );
    }
    const unused = customAllowPermissions(permissions).filter(
      (permission) =>
        ![...commands].some(
          (command) => allowPermission(command) === permission,
        ),
    );
    expect(unused).toEqual([]);
  });

  it("keeps extract windows to their explicit core APIs", () => {
    const { permissions } = readCapability("extract");

    expect(permissions).toEqual(
      expect.arrayContaining([
        "core:event:allow-listen",
        "core:event:allow-unlisten",
        "core:window:allow-close",
        "core:window:allow-minimize",
        "core:window:allow-start-dragging",
        "allow-load-settings",
        "allow-set-workspace-window-fx",
        "allow-supports-workspace-window-fx",
      ]),
    );
    expect(permissions).not.toContain("core:default");
    expect(permissions).not.toContain("dialog:allow-confirm");
  });

  it("keeps the debug console window to listen plus an allowlisted signal relay", () => {
    const source = fs.readFileSync(
      path.resolve(process.cwd(), "src", "debug-console-window.ts"),
      "utf8",
    );
    const commands = [
      ...source.matchAll(/invoke(?:<[^>]+>)?\(\s*["'](\w+)["']/g),
    ].map((match) => match[1]);
    expect(commands).toContain("relay_debug_console_signal");

    const { permissions } = readCapability("debug-console");
    const granted = new Set(permissions);
    for (const command of new Set(commands)) {
      const allow = `allow-${command.replaceAll("_", "-")}`;
      expect(granted, `debug console invokes ${command}`).toContain(allow);
    }
    expect(permissions).toContain("allow-relay-debug-console-signal");
    expect(permissions).not.toContain("core:event:allow-emit");
    expect(permissions).not.toContain("allow-run-7z");
    expect(permissions).not.toContain("allow-open-path");
    expect(permissions).not.toContain("updater:allow-check");
  });
});
